### ISSUE TITLE
Use .hex instead of hsl_to_hex()

### ISSUE THREAD

**Issue by rktjmp** [adisen99/codeschool.nvim#1]
Hey, I saw this bug on gruvbox and went looking to see if anyone else would be effected.

I saw you already patched the renamed module but you may want to mirror the patch linked below to avoid any future breakage. The modules not exposed by `require("lush")` are technically considered private and may change.

https://github.com/npxbr/gruvbox.nvim/pull/55#issuecomment-869212855

https://github.com/npxbr/gruvbox.nvim/pull/55/files

**Comment by adisen99** [comment]
@rktjmp  Alright, I will make the changes. Thanks for the heads-up.

**Comment by adisen99** [comment]
@rktjmp I have mirrored the changes as the patch linked above. So closing this issue. Will take a look at the Lush API documentation as well to see the new changes. Thanks for all the work with `lush.nvim`.

Please fill free to re-open the issue if any more changes are needed.
