### ISSUE TITLE
vim.g.codeschool_transparent_bg is non-existent

### ISSUE THREAD

**Issue by wimstefan** [adisen99/codeschool.nvim#2]
Well the title says it all - it is [mentioned in the Wiki](https://github.com/adisen99/codeschool.nvim/wiki/Configuration#vimgcodeschool_transparent_bg) but that's it.
It would be a very nice feature to have though - I'm selecting my colourschemes by their ability for background transparency ;)

**Comment by adisen99** [comment]
The issue is fixed in the latest commit. Please check. If all is fine, then I will close the issue.

**Comment by wimstefan** [comment]
Looking good :)
Thank you so much for enabling this feature!
